import { writeFileSync, mkdirSync, existsSync, unlinkSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

const COMPANION_BIN_DIR = join(homedir(), ".companion", "bin");
const SKILL_DIR = join(homedir(), ".claude", "skills", "quest");
const OLD_SLASH_COMMAND = join(homedir(), ".claude", "commands", "quest.md");
const OLD_API_DOC = join(homedir(), ".companion", "questmaster", "API.md");

/**
 * Set up Questmaster CLI integration on server startup:
 * 1. Write a wrapper script at ~/.companion/bin/quest
 * 2. Write an agent skill at ~/.claude/skills/quest/SKILL.md
 * 3. Clean up old files (slash command, API.md)
 */
export function ensureQuestmasterIntegration(port: number, packageRoot: string): void {
  writeWrapperScript(packageRoot);
  writeAgentSkill();
  cleanupOldFiles();
  console.log("[quest-integration] CLI wrapper and agent skill installed");
}

function writeWrapperScript(packageRoot: string): void {
  mkdirSync(COMPANION_BIN_DIR, { recursive: true });

  const questScript = join(packageRoot, "bin", "quest.ts");
  const wrapperPath = join(COMPANION_BIN_DIR, "quest");

  // Use bun to run the quest.ts script directly
  const wrapper = `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
exec bun "${questScript}" "$@"
`;

  writeFileSync(wrapperPath, wrapper, "utf-8");
  chmodSync(wrapperPath, 0o755);
}

function writeAgentSkill(): void {
  mkdirSync(SKILL_DIR, { recursive: true });

  const skillPath = join(SKILL_DIR, "SKILL.md");

  const content = `---
name: quest
description: "Manage persistent, cross-session quests tracked by The Companion. NOT the built-in TodoWrite — quests persist across sessions, are visible to humans in the Companion UI, and have a lifecycle (idea/refined/in_progress/needs_verification/done). Users often say 'tasks', 'todos', or 'quests' interchangeably — if they say 'check my tasks', 'what are my todos', or 'what should I work on', they mean quests. Load this skill whenever the user mentions quests, tasks, todos, questmaster, or asks what to work on."
---

<!-- Auto-generated by Companion server. Do not edit. -->

# Questmaster — Persistent Cross-Session Quest Tracking

The \`quest\` CLI manages **quests**: persistent tasks tracked by The Companion across sessions.

## Quests vs Built-in TodoWrite

These are completely different systems. Do NOT confuse them.

| | **Quests** (this skill) | **TodoWrite** (built-in) |
|---|---|---|
| **Scope** | Cross-session, persistent on disk | Single session, ephemeral |
| **Lifecycle** | idea → refined → in_progress → needs_verification → done | pending → in_progress → completed |
| **Visibility** | Visible to humans in Companion UI, shared across all sessions | Only visible in current conversation |
| **Purpose** | Project-level work items assigned by humans, tracked over time | Breaking down your immediate work into steps |
| **Who creates** | Humans (or agents, then refined by humans) | You, the agent, to organize current work |
| **Verification** | Human reviews verification checklist before marking done | Self-managed by agent |

**Rule of thumb**: Users often say "tasks", "todos", or "quests" interchangeably when referring to quests. If the user says "check my tasks", "what are my todos", or "what should I work on", they mean **quests** — check them with \`quest list\`. Only use **TodoWrite** for your own internal progress tracking on the current task.

## Commands

\`\`\`
quest list   [--status <s>] [--json]                          List quests
quest show   <id> [--json]                                    Show quest detail
quest history <id> [--json]                                   Show version history
quest tags   [--json]                                         List all existing tags with counts
quest create <title> [--desc "..."] [--tags "t1,t2"] [--json] Create a quest
quest claim  <id> [--session <sid>] [--json]                  Claim for your session
quest complete <id> --items "c1,c2" [--json]                  Submit for verification
quest done   <id> [--notes "..."] [--cancelled] [--json]      Mark as done/cancelled
quest transition <id> --status <s> [--desc "..."] [--json]    Change status
quest edit   <id> [--title "..."] [--desc "..."] [--json]     Edit in place
quest check  <id> <index> [--json]                            Toggle verification item
quest delete <id> [--json]                                    Delete quest
\`\`\`

## Typical workflow

1. See what's available: \`quest list --status refined\`
2. Claim a quest: \`quest claim q-N\` (uses your session ID automatically)
3. Do the work (use TodoWrite to track your own sub-steps if needed)
4. Submit for verification: \`quest complete q-N --items "Tests pass,Typecheck passes,Docs updated"\`
5. The human reviews in the Companion UI and marks done

## Tags

**Always reuse existing tags.** Before creating or editing a quest, run \`quest tags\` to see what tags already exist. Only introduce a new tag when no existing tag fits. This keeps the tag space consistent and filterable.

Every quest should have at least one tag. Common patterns: component/area (e.g. "questmaster", "ws-bridge", "ui"), type (e.g. "bugfix", "feature", "refactor"), or concern (e.g. "mobile", "performance").

## Images

Quests can have attached images stored at \`~/.companion/questmaster/images/\`.
When a quest has images, \`quest show\` displays the file paths.
Use the Read tool to view images — they are standard image files on disk.

## Environment

- \`COMPANION_SESSION_ID\` is set automatically — \`quest claim\` uses it by default
- \`COMPANION_PORT\` is set automatically — the CLI uses it for browser notifications
- Pass \`--json\` to any command for machine-parseable output
- If \`quest\` is not found on PATH, use the full path: \`~/.companion/bin/quest\`

## Status flow and transition guidelines

\`\`\`
idea → refined → in_progress → needs_verification → done
                      ↑                |
                      └────────────────┘  (rework)
\`\`\`

**Never skip states or jump directly to \`done\`.** Before proposing any transition, consider:

### idea → refined (MUST polish the quest)
When transitioning from idea to refined, you **must** also clean up the quest:

1. **Title**: Make it concise and to the point — aim for under 10 words. If the original title is a sentence or contains implementation details, shorten it to a clear summary.
2. **Description**: Move any detail from the title into the description. Flesh out the description so it is clear and actionable. Define what "done" looks like.
3. **Tags**: Run \`quest tags\` to see existing tags. Reuse existing tags when they fit. Only create a new tag when no existing tag is appropriate. Every quest should have at least one tag.
4. Use \`quest edit <id> --title "..." --desc "..." --tags "t1,t2"\` to apply these changes.

Example: If an idea has title "The quest tool should show existing tags so agents reuse them consistently" with no tags, you would:
- Title → "Show existing tags in quest tool"
- Description → the original long title + any additional context about why and how
- Tags → check \`quest tags\`, reuse e.g. "questmaster" if it exists, or "tooling"

Also check:
- Are there open questions that need the human's input first?

### refined → in_progress (also polish if needed)
- Has the quest been claimed by a session (\`quest claim\`)?
- If the title/description/tags still need cleanup (e.g. quest was created as refined directly), apply the same polishing rules as idea → refined.
- Do you understand the full scope of work?
- Are there dependencies or blockers to flag?

### in_progress → needs_verification
- Is the implementation actually complete (not partially done)?
- Have you run tests, typecheck, and linting?
- What manual verification does the human need to do? Always propose specific verification items via \`quest complete --items "..."\`. Think about what you CANNOT verify yourself — UI appearance, UX feel, cross-browser behavior, edge cases that need human judgment, deployment concerns, etc.
- Did you consider side effects or regressions in related features?

### needs_verification → done
- **Only the human should mark quests as done**, after reviewing verification items. Never transition to \`done\` yourself unless the human explicitly asks you to.
- When marking done (by human request), always include \`--notes\` with high-info-density closure notes: which commits contain the changes (exact hashes), why it's done, any caveats or follow-ups. Example: \`quest done q-3 --notes "Implemented in commits abc1234, def5678. Added image upload UI, CLI display, and REST endpoints. Follow-up: consider image compression."\`
- Use \`--cancelled\` if the quest is being abandoned/aborted rather than completed. Always include \`--notes\` explaining why cancelled. Example: \`quest done q-5 --cancelled --notes "Superseded by q-7 which takes a different approach."\`

### needs_verification → in_progress (rework)
- The human found issues during verification. Re-read their feedback before resuming work.
`;

  writeFileSync(skillPath, content, "utf-8");
}

function cleanupOldFiles(): void {
  // Remove old slash command (superseded by agent skill)
  if (existsSync(OLD_SLASH_COMMAND)) {
    try {
      unlinkSync(OLD_SLASH_COMMAND);
    } catch {
      // Ignore
    }
  }
  // Remove old API.md (superseded by CLI)
  if (existsSync(OLD_API_DOC)) {
    try {
      unlinkSync(OLD_API_DOC);
    } catch {
      // Ignore
    }
  }
}
