import { writeFileSync, mkdirSync, existsSync, unlinkSync, chmodSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

const COMPANION_BIN_DIR = join(homedir(), ".companion", "bin");
const LOCAL_BIN_DIR = join(homedir(), ".local", "bin");
const CLAUDE_SKILL_DIR = join(homedir(), ".claude", "skills", "quest");
const CODEX_SKILL_DIR = join(homedir(), ".codex", "skills", "quest");
const OLD_SLASH_COMMAND = join(homedir(), ".claude", "commands", "quest.md");
const OLD_API_DOC = join(homedir(), ".companion", "questmaster", "API.md");
const TEMPLATE_PATH = join(dirname(fileURLToPath(import.meta.url)), "templates", "quest-skill-docs.md");

let questSkillDocsTemplate: string | null = null;

async function getQuestSkillDocsTemplate(): Promise<string> {
  if (questSkillDocsTemplate !== null) return questSkillDocsTemplate;
  questSkillDocsTemplate = await readFile(TEMPLATE_PATH, "utf-8");
  return questSkillDocsTemplate;
}

/**
 * Set up Questmaster CLI integration on server startup:
 * 1. Write a wrapper script at ~/.companion/bin/quest
 * 2. Write an agent skill for both Claude and Codex skill homes
 * 3. Clean up old files (slash command, API.md)
 */
export async function ensureQuestmasterIntegration(port: number, packageRoot: string): Promise<void> {
  void port;
  writeWrapperScript(packageRoot);
  writeLocalPathShim();
  writeRipgrepShim();
  const skillContent = await getQuestSkillDocsTemplate();
  writeAgentSkill(CLAUDE_SKILL_DIR, skillContent);
  writeAgentSkill(CODEX_SKILL_DIR, skillContent);
  cleanupOldFiles();
  console.log("[quest-integration] CLI wrapper and agent skill installed");
}

function writeWrapperScript(packageRoot: string): void {
  mkdirSync(COMPANION_BIN_DIR, { recursive: true });

  const questScript = join(packageRoot, "bin", "quest.ts");
  const wrapperPath = join(COMPANION_BIN_DIR, "quest");

  // Use bun to run the quest.ts script directly
  const wrapper = `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
if command -v bun >/dev/null 2>&1; then
  exec bun "${questScript}" "$@"
fi

if [ -x "$HOME/.bun/bin/bun" ]; then
  export PATH="$HOME/.bun/bin:$PATH"
  exec "$HOME/.bun/bin/bun" "${questScript}" "$@"
fi

echo "quest: bun not found (looked in PATH and \$HOME/.bun/bin/bun)" >&2
exit 127
`;

  writeFileSync(wrapperPath, wrapper, "utf-8"); // sync-ok: quest setup, not called during message handling
  chmodSync(wrapperPath, 0o755); // sync-ok: quest setup, not called during message handling
}

function writeLocalPathShim(): void {
  mkdirSync(LOCAL_BIN_DIR, { recursive: true });
  const shimPath = join(LOCAL_BIN_DIR, "quest");
  const shim = `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
exec "$HOME/.companion/bin/quest" "$@"
`;

  writeFileSync(shimPath, shim, "utf-8"); // sync-ok: quest setup, not called during message handling
  chmodSync(shimPath, 0o755); // sync-ok: quest setup, not called during message handling
}

function writeRipgrepShim(): void {
  mkdirSync(LOCAL_BIN_DIR, { recursive: true });
  const shimPath = join(LOCAL_BIN_DIR, "rg");
  const shim = `#!/bin/bash
# Auto-generated by Companion server. Do not edit.

# Prefer a real ripgrep binary when present.
for candidate in /usr/bin/rg /usr/local/bin/rg "$HOME/.cargo/bin/rg" "$HOME/.nix-profile/bin/rg"; do
  if [ -x "$candidate" ]; then
    exec "$candidate" "$@"
  fi
done

if [ "$1" = "--version" ] || [ "$1" = "-V" ]; then
  echo "rg (companion shim) 0.0.0"
  echo "fallback: grep/find compatibility mode"
  exit 0
fi

if [ "$1" = "--files" ]; then
  shift
  root="\${1:-.}"
  find "$root" -type f -not -path '*/.git/*' | sed 's#^\\./##'
  exit 0
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  echo "rg (companion shim): partial compatibility mode using grep/find"
  echo "supports: --version, --files, and common search flags"
  exit 0
fi

if [ "$#" -lt 1 ]; then
  echo "rg shim: usage: rg [OPTIONS] PATTERN [PATH ...] or rg --files [PATH]" >&2
  exit 2
fi

grep_args=(
  -R
  -I
  -n
  -E
  --binary-files=without-match
  --exclude-dir=.git
)
positional=()

while [ "$#" -gt 0 ]; do
  case "$1" in
    --)
      shift
      while [ "$#" -gt 0 ]; do
        positional+=("$1")
        shift
      done
      break
      ;;
    --hidden|-uu|-uuu)
      # Ignored: grep -R already walks hidden paths by default.
      shift
      ;;
    --glob|-g)
      if [ "$#" -lt 2 ]; then
        echo "rg shim: $1 requires a pattern argument" >&2
        exit 2
      fi
      grep_args+=(--include "$2")
      shift 2
      ;;
    -g*)
      grep_args+=(--include "$\{1#-g}")
      shift
      ;;
    -n|-S)
      # -n is already enabled, -S (smart case) is not supported.
      shift
      ;;
    -F|-i|-w|-x|-v|-l|-L|-c|-o|-s|-h|-H)
      grep_args+=("$1")
      shift
      ;;
    -e|-f)
      if [ "$#" -lt 2 ]; then
        echo "rg shim: $1 requires an argument" >&2
        exit 2
      fi
      grep_args+=("$1" "$2")
      shift 2
      ;;
    -*)
      grep_args+=("$1")
      shift
      ;;
    *)
      positional+=("$1")
      shift
      ;;
  esac
done

if [ "$\{#positional[@]}" -lt 1 ]; then
  echo "rg shim: missing PATTERN" >&2
  exit 2
fi

pattern="$\{positional[0]}"
if [ "$\{#positional[@]}" -eq 1 ]; then
  positional+=(.)
fi

exec grep "$\{grep_args[@]}" -- "$pattern" "$\{positional[@]:1}"
`;

  writeFileSync(shimPath, shim, "utf-8"); // sync-ok: quest setup, not called during message handling
  chmodSync(shimPath, 0o755); // sync-ok: quest setup, not called during message handling
}

function writeAgentSkill(skillDir: string, content: string): void {
  mkdirSync(skillDir, { recursive: true });
  const skillPath = join(skillDir, "SKILL.md");
  writeFileSync(skillPath, content, "utf-8"); // sync-ok: quest setup, not called during message handling
}

function cleanupOldFiles(): void {
  // Remove old slash command (superseded by agent skill)
  if (existsSync(OLD_SLASH_COMMAND)) {
    // sync-ok: quest setup, not called during message handling
    try {
      unlinkSync(OLD_SLASH_COMMAND); // sync-ok: quest setup, not called during message handling
    } catch {
      // Ignore
    }
  }
  // Remove old API.md (superseded by CLI)
  if (existsSync(OLD_API_DOC)) {
    // sync-ok: quest setup, not called during message handling
    try {
      unlinkSync(OLD_API_DOC); // sync-ok: quest setup, not called during message handling
    } catch {
      // Ignore
    }
  }
}
