import { writeFileSync, mkdirSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

const COMPANION_BIN_DIR = join(homedir(), ".companion", "bin");
const CLAUDE_SKILL_DIR = join(homedir(), ".claude", "skills", "takode-orchestration");
const CODEX_SKILL_DIR = join(homedir(), ".codex", "skills", "takode-orchestration");

/**
 * Set up Takode orchestration CLI integration on server startup:
 * 1. Write a wrapper script at ~/.companion/bin/takode
 * 2. Write an agent skill for both Claude and Codex skill homes
 */
export function ensureTakodeIntegration(packageRoot: string): void {
  writeWrapperScript(packageRoot);
  writeAgentSkill(CLAUDE_SKILL_DIR);
  writeAgentSkill(CODEX_SKILL_DIR);
  console.log("[takode-integration] CLI wrapper and agent skill installed");
}

function writeWrapperScript(packageRoot: string): void {
  mkdirSync(COMPANION_BIN_DIR, { recursive: true });
  const takodeScript = join(packageRoot, "bin", "takode.ts");
  const wrapperPath = join(COMPANION_BIN_DIR, "takode");

  const wrapper = `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
if command -v bun >/dev/null 2>&1; then
  exec bun "${takodeScript}" "$@"
fi

if [ -x "$HOME/.bun/bin/bun" ]; then
  export PATH="$HOME/.bun/bin:$PATH"
  exec "$HOME/.bun/bin/bun" "${takodeScript}" "$@"
fi

echo "takode: bun not found (looked in PATH and \\$HOME/.bun/bin/bun)" >&2
exit 127
`;

  writeFileSync(wrapperPath, wrapper, "utf-8"); // sync-ok: takode setup, not called during message handling
  chmodSync(wrapperPath, 0o755); // sync-ok: takode setup, not called during message handling
}

function writeAgentSkill(skillDir: string): void {
  mkdirSync(skillDir, { recursive: true });
  const skillPath = join(skillDir, "SKILL.md");

  const content = `---
name: takode-orchestration
description: "Cross-session orchestration for Takode orchestrator sessions. Use when you need to coordinate multiple agent sessions: watching events, peeking at session activity, reading messages, sending instructions to workers, or listing active sessions. Only available when TAKODE_ROLE=orchestrator is set. Triggers: 'watch sessions', 'check on workers', 'send to session', 'orchestrate', 'coordinate agents', 'list sessions', 'peek at session', 'what are my sessions doing'."
---

<!-- Auto-generated by Companion server. Do not edit. -->

# Takode — Cross-Session Orchestration

You are an **orchestrator agent**. You coordinate multiple worker sessions, monitor their progress, and decide when to intervene, send follow-up instructions, or notify the human.

## Environment

- \`TAKODE_ROLE=orchestrator\` — confirms you have orchestration privileges
- \`TAKODE_API_PORT\` — the Companion server port (used automatically by the CLI)
- \`COMPANION_SESSION_ID\` — your own session ID
- The \`takode\` command is available at \`~/.companion/bin/takode\` (or on PATH)
- Works with both **Claude Code** and **Codex** sessions — the CLI talks to the Companion server, not to any backend directly

## Commands

### \`takode list [--all] [--json]\`

List all active sessions with their status, name, model, and last activity.

\`\`\`bash
# Show active sessions (default)
takode list

# Show all sessions including archived
takode list --all
\`\`\`

Output shows session number (#N), status, name, role, model, branch, and last activity. Use the session number (#N) in all other commands.

### \`takode search <query> [--all] [--json]\`

Search sessions by name, keyword, task title, branch, message, or path.

\`\`\`bash
# Search for sessions related to "auth"
takode search auth

# Search including archived sessions
takode search jwt --all
\`\`\`

Searches across: session name, task history titles, auto-extracted keywords, git branch, last message preview, working directory, and repo root.

### \`takode watch --sessions <ids> [--timeout <secs>] [--since <cursor>] [--all-events] [--json]\`

Block and wait for actionable events from specific sessions. Returns when events arrive or timeout (default 120s).

**By default, only actionable events are shown** — things a human would be notified about. Intermediate events (turn_start, permission auto-approved, permission_resolved) are filtered out to avoid waking the orchestrator unnecessarily.

\`\`\`bash
# Watch sessions #1 and #2 (actionable events only)
takode watch --sessions 1,2

# Watch with longer timeout
takode watch --sessions 1,2,3 --timeout 300

# Resume from last event cursor
takode watch --sessions 1,2 --since 42

# Include ALL events (turn_start, permission_resolved, etc.)
takode watch --sessions 1,2 --all-events
\`\`\`

**Drain-then-block behavior**: If events arrived since your last \`watch\`, they're returned immediately as a batch. Otherwise, blocks until the next event or timeout.

**Default actionable events** (shown by default):
| Event | Meaning |
|---|---|
| \`turn_end\` | Worker finished generating. Shows tools used and result preview. |
| \`permission_request\` | Worker needs human approval (only fires after auto-approval defers). |
| \`quest_update\` | A quest was updated (any session). |
| \`session_disconnected\` | Worker CLI disconnected. |
| \`session_error\` | Worker turn ended with an error. |
| \`user_message\` | New user message arrived in a watched session. |

**Additional events** (shown with \`--all-events\`):
| Event | Meaning |
|---|---|
| \`turn_start\` | Worker started generating (not usually actionable). |
| \`permission_resolved\` | Permission was approved or denied (already handled). |

**\`--sessions\` is required.** Always specify which sessions you're watching. Use \`takode list\` first to discover session numbers.

### \`takode tasks <session> [--json]\`

Show the task outline (table of contents) for a session's conversation history. Tasks are automatically detected by the session auto-namer and quest system.

\`\`\`bash
takode tasks 1
\`\`\`

Output shows each task with its title, start time, and message ID range:
\`\`\`
  #  Started   Task                                              Msg Range
  ──────────────────────────────────────────────────────────────────────────────
   1  07:13     Explore existing CLI for session interaction       [0]-[36]
   2  07:36     Design cross-session orchestration system          [37]-[98]
   3  08:23     Refine design with user feedback                   [99]-[420]
\`\`\`

Use the message ranges with \`takode peek <session> --from <msg-id>\` to browse a specific task, or use \`takode peek <session> --task <n>\` as a shortcut.

**Tip:** Run \`takode tasks\` first when investigating an unfamiliar session — it gives you a high-level map of what the agent has been working on, organized by task boundaries.

### \`takode peek <session> [--from N] [--count N] [--detail --turns N] [--json]\`

View session activity with progressive detail. Three modes:

**Default mode** (smart overview):
\`\`\`bash
takode peek 1
\`\`\`
Shows a smart overview: recent completed turns as collapsed one-liners (with stats and result preview), plus the last turn expanded with up to 10 messages. This is your primary monitoring command — covers broad context with minimal tokens.

Output includes:
- **Total turn/message count** and message ID range
- **Collapsed turns** — one line each: turn number, time range, tool count, success indicator, result preview
- **Expanded last turn** — full messages with \`[N]\` IDs, timestamps, tool tree, result
- **Omission counts** when earlier turns or messages are hidden

**Range browsing** (paged history):
\`\`\`bash
# Browse messages starting at index 500
takode peek 1 --from 500

# Browse 50 messages from index 500
takode peek 1 --from 500 --count 50
\`\`\`
Shows ~30 messages around the given index with full detail and turn boundaries. Output includes prev/next hints for continued browsing. Use this to navigate backwards through a session's history.

**Detail mode** (legacy full detail):
\`\`\`bash
# Full detail on last 3 turns
takode peek 1 --detail --turns 3
\`\`\`

#### Navigation workflow

\`\`\`
1. takode tasks 1              → Table of contents: tasks with msg ranges
2. takode peek 1               → Overview: collapsed turns + expanded last turn
3. takode peek 1 --task 3      → Browse task 3's messages
4. takode peek 1 --from 800    → Browse messages [800]-[830] in detail
5. takode read 1 815           → Full content of message 815
\`\`\`

### \`takode read <session> <msg-id> [--offset N] [--limit N] [--json]\`

Read full content of a specific message, with line numbers and pagination.

\`\`\`bash
# Read message #42 from session #1
takode read 1 42

# Paginate through a long message
takode read 1 42 --offset 0 --limit 50
takode read 1 42 --offset 50 --limit 50
\`\`\`

This works exactly like the Read tool for files — line numbers on the left, offset/limit for pagination. Use this when \`peek\` shows a truncated message you need to see in full.

### \`takode send <session> <message>\`

Send a message to a worker session (injected as a user message).

\`\`\`bash
# Send follow-up instructions
takode send 2 "Please also add tests for the edge cases"

# Send to session by number
takode send 1 "Good work. Now refactor the auth middleware."
\`\`\`

The worker will receive this as if the human typed it. It triggers a new turn.

## Orchestration Workflow

### 1. Discover sessions

\`\`\`bash
takode list
\`\`\`

Note the session numbers (#N) you want to manage.

### 2. Main event loop

\`\`\`
while there is work to do:
  events = takode watch --sessions <ids>

  for each event:
    if turn_end:
      output = takode peek <session>
      # Review output, decide next steps
      # Option A: send follow-up work
      # Option B: the worker is done, notify human
      # Option C: nothing to do, continue watching

    if session_error:
      output = takode peek <session> --turns 2
      # Diagnose the error, maybe send recovery instructions

    if permission_request:
      # The human will handle permissions in the browser
      # You can note this and continue watching

    if quest_update:
      # A quest changed state — check if relevant to your work
\`\`\`

### 3. Progressive information reveal

To protect your context window during long orchestration:

1. **Start with \`peek\`** — see the compact summary first
2. **Drill into specific messages with \`read\`** — only when the summary isn't enough
3. **Paginate long messages** — use \`--offset\`/\`--limit\` just like reading files
4. **Watch events, don't poll** — \`watch\` blocks efficiently instead of repeatedly calling \`peek\`

### 4. Coordinate with quests

Use the \`quest\` CLI alongside \`takode\` for task tracking:

\`\`\`bash
# Check what quests are in progress
quest list --status in_progress

# After a worker finishes, transition the quest
quest transition q-42 --status needs_verification

# Leave feedback on a quest
quest feedback q-42 --text "Auth implementation looks good, but needs rate limiting"
\`\`\`

## Session Identification

Commands accept multiple formats for session IDs:
- **Integer number**: \`1\`, \`3\`, \`5\` — the short form from \`takode list\`
- **UUID prefix**: \`abc123\` — first chars of the full UUID
- **Full UUID**: \`550e8400-e29b-41d4-a716-446655440000\`

Prefer integer numbers — they're stable within a server session and easy to type.

## Tips

_This section will grow as we learn from real orchestration usage._

- **Keep your watch loop tight.** Process each event, decide quickly, and go back to watching. Don't do heavy computation between events.
- **Use \`--json\` for programmatic decisions.** When you need to branch on event data, parse JSON output instead of text.
- **Don't micro-manage workers.** Send clear instructions and let them work. Only intervene on errors or when they finish a major step.
- **Batch related messages.** If you need to send context + instructions to a worker, send it as one message rather than multiple.
- **Monitor context usage.** Long orchestration sessions accumulate context. Use \`peek\` (truncated) over \`read\` (full) whenever possible.
- **Track event cursors.** When using \`watch --since\`, pass the last event ID to avoid re-processing events.
- **Mixed backends work seamlessly.** You can orchestrate both Claude Code and Codex sessions from either backend. The \`takode\` CLI talks to the Companion server, so the worker's backend is transparent to you.
- **Watch auto-includes your own session.** When you run \`takode watch\`, human messages to your session will interrupt the watch so you stay responsive. Process the human's input first, then resume watching.
`;

  writeFileSync(skillPath, content, "utf-8"); // sync-ok: takode setup, not called during message handling
}
