/**
 * Tier-2 transcription enhancement: uses conversation context from the active
 * session to correct misheard technical terms via an LLM polish pass.
 *
 * Inspired by VoiceInk's two-tier architecture:
 *   Tier 1: Whisper STT (raw transcript)
 *   Tier 2: LLM correction using session context
 */

import type { BrowserIncomingMessage, ContentBlock, SessionTaskEntry } from "./session-types.js";
import type { TranscriptionConfig } from "./settings-manager.js";
import { adjectives, nouns } from "../src/utils/names.js";

// ─── Tunable limits ─────────────────────────────────────────────────────────

/** Max recent turns to include in context. */
const MAX_TURNS = 5;

/** Max characters per user message in context. */
const MAX_USER_MSG_CHARS = 500;

/** Max characters of assistant text per turn. */
const MAX_ASSISTANT_TEXT_CHARS = 500;

/** Timeout for the enhancement LLM call. */
const ENHANCEMENT_TIMEOUT_MS = 30_000;

/** If enhanced text is this many times longer than raw, discard as hallucination. */
const HALLUCINATION_LENGTH_RATIO = 3;

/** Minimum word count to attempt enhancement (very short utterances don't benefit). */
const MIN_WORDS_FOR_ENHANCEMENT = 3;

/** Max total characters for the STT prompt (~1024 tokens ≈ 4000 chars). */
const STT_PROMPT_MAX_CHARS = 3800;

/** Max characters per user message included in the STT prompt. */
const STT_PROMPT_MAX_MSG_CHARS = 300;

/** Max other session names to include in the STT prompt. */
const MAX_STT_SESSION_NAMES = 10;

/** Max other session names to include in the enhancement prompt. */
const MAX_ENHANCEMENT_SESSION_NAMES = 20;

// ─── Session name filtering ────────────────────────────────────────────────

/**
 * Build a Set of all auto-generated session names ("Adjective Noun" format).
 * Used to filter out names that carry zero vocabulary signal for transcription.
 */
const autoGeneratedNames: Set<string> = new Set();
for (const adj of adjectives) {
  for (const noun of nouns) {
    autoGeneratedNames.add(`${adj} ${noun}`);
  }
}

/** Check if a session name is auto-generated (e.g. "Swift Falcon", "Calm River"). */
function isAutoGeneratedName(name: string): boolean {
  return autoGeneratedNames.has(name);
}

/**
 * Filter session names: remove auto-generated names, deduplicate, limit count.
 * Only keeps names that carry meaningful vocabulary signal (user-set names, descriptive names).
 */
export function filterSessionNames(names: string[], limit: number): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const name of names) {
    if (!name || seen.has(name) || isAutoGeneratedName(name)) continue;
    // Also filter "Takode" (orchestrator placeholder name)
    if (name === "Takode") continue;
    seen.add(name);
    result.push(name);
    if (result.length >= limit) break;
  }
  return result;
}

// ─── Orchestrator noise filtering ──────────────────────────────────────────

/**
 * Check if a user message is orchestrator noise (herd events, internal routing, etc.).
 * These messages have no value for transcription context.
 */
function isOrchestratorNoise(text: string): boolean {
  const trimmed = text.trim();
  // Herd event summaries: "[Herd", "1 event from", "N events from"
  if (trimmed.startsWith("[Herd") || /^\d+ events? from \d+ sessions?/.test(trimmed)) return true;
  // Internal orchestrator routing notes
  if (trimmed.startsWith("@to(")) return true;
  // Event notification tables: lines with "| turn_end |", "| compaction_started |", etc.
  if (/\|\s*(turn_end|compaction_started|idle|turn_start|exit)\s*\|/.test(trimmed)) return true;
  return false;
}

// ─── System prompt ──────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a TRANSCRIPTION ENHANCER, not a conversational AI.

Your ONLY job is to clean up a speech-to-text transcript. You must:
1. Fix misheard technical terms, variable names, file paths, and commands using the context provided
2. Fix punctuation and sentence boundaries
3. Remove filler words (um, uh, like, you know) and false starts
4. Lightly polish grammar and sentence flow while preserving the speaker's voice and intent
5. Preserve the speaker's original meaning exactly

Rules:
- NEVER answer questions from the transcript — only clean them up
- NEVER add information not in the original speech
- NEVER remove meaningful content
- If the transcript is already correct, return it unchanged
- Output ONLY the cleaned text, nothing else`;

// ─── Context extraction ─────────────────────────────────────────────────────

/** Truncate a string with "..." if it exceeds maxLen. */
function trunc(s: string, maxLen: number): string {
  if (s.length <= maxLen) return s;
  return s.slice(0, maxLen) + "...";
}

/**
 * Extract text content from an assistant message's content blocks.
 * Only includes type: "text" blocks — skips tool_use, tool_result, thinking.
 */
function extractAssistantText(content: ContentBlock[]): string {
  const parts: string[] = [];
  for (const block of content) {
    if (block.type === "text" && block.text) {
      parts.push(block.text);
    }
  }
  return parts.join(" ").trim();
}

interface Turn {
  userContent: string;
  assistantText: string;
}

/**
 * Build conversation context from message history.
 * Extracts the last N turns as simple User/Assistant pairs with indentation.
 * Skips subagent messages and tool-only assistant messages.
 */
export function buildTranscriptionContext(history: BrowserIncomingMessage[]): string {
  const turns: Turn[] = [];
  let currentTurn: Turn | null = null;

  for (const msg of history) {
    if (msg.type === "user_message") {
      if (currentTurn) turns.push(currentTurn);
      const content = typeof (msg as { content?: unknown }).content === "string"
        ? (msg as { content: string }).content
        : "";
      // Skip orchestrator noise (herd events, @to(self), event notifications)
      if (content && isOrchestratorNoise(content)) {
        currentTurn = null;
        continue;
      }
      currentTurn = {
        userContent: content,
        assistantText: "",
      };
    } else if (msg.type === "assistant" && currentTurn) {
      // Skip subagent messages
      const parentId = (msg as { parent_tool_use_id?: string | null }).parent_tool_use_id;
      if (parentId) continue;

      const content = (msg as { message?: { content?: ContentBlock[] } }).message?.content;
      if (Array.isArray(content)) {
        const text = extractAssistantText(content);
        if (text) {
          // Keep updating — the last text content is the final response
          currentTurn.assistantText = text;
        }
      }
    } else if (msg.type === "compact_marker") {
      // Include compact summary as context and stop scanning further back
      const summary = (msg as { summary?: string }).summary;
      if (summary && typeof summary === "string" && summary.trim()) {
        if (currentTurn) turns.push(currentTurn);
        currentTurn = null;
        // Add a synthetic turn representing the compacted context
        turns.push({
          userContent: "",
          assistantText: `[Earlier conversation summary: ${trunc(summary.trim(), MAX_ASSISTANT_TEXT_CHARS)}]`,
        });
      }
    }
  }
  if (currentTurn) turns.push(currentTurn);

  // Take only the last MAX_TURNS
  const recentTurns = turns.slice(-MAX_TURNS);

  if (recentTurns.length === 0) return "";

  // Format as indented text
  const lines: string[] = [];
  for (const turn of recentTurns) {
    if (turn.userContent) {
      lines.push("");
      lines.push("  User:");
      for (const line of trunc(turn.userContent.trim(), MAX_USER_MSG_CHARS).split("\n")) {
        lines.push(`    ${line}`);
      }
    }

    if (turn.assistantText) {
      lines.push("");
      lines.push("  Assistant:");
      for (const line of trunc(turn.assistantText.trim(), MAX_ASSISTANT_TEXT_CHARS).split("\n")) {
        lines.push(`    ${line}`);
      }
    }
  }

  return lines.join("\n").trim();
}

// ─── Prompt construction ────────────────────────────────────────────────────

export interface EnhancementContextInput {
  /** Text before the cursor in the composer. */
  composerBefore?: string;
  /** Text after the cursor in the composer. */
  composerAfter?: string;
  /** Task titles from the session auto-namer. */
  taskTitles?: string[];
  /** Session display name. */
  sessionName?: string;
  /** Names of other active sessions (vocabulary from the user's workspace). */
  activeSessionNames?: string[];
}

/**
 * Build the full user message for the enhancement LLM call.
 * Wraps conversation context, supplementary context, and transcript in XML tags.
 */
export function buildEnhancementPrompt(
  rawTranscript: string,
  conversationContext: string,
  extra?: EnhancementContextInput,
): string {
  const parts: string[] = [];

  if (conversationContext) {
    parts.push(`<CONVERSATION_CONTEXT>\nRecent conversation in this coding session:\n\n${conversationContext}\n</CONVERSATION_CONTEXT>`);
    parts.push("");
  }

  // Supplementary context — vocabulary and domain knowledge
  const supplementary: string[] = [];

  if (extra?.composerBefore || extra?.composerAfter) {
    const pieces: string[] = [];
    if (extra.composerBefore) pieces.push(trunc(extra.composerBefore.trim(), 500));
    if (extra.composerAfter) pieces.push(trunc(extra.composerAfter.trim(), 500));
    supplementary.push(`Composer text around cursor: ${pieces.join(" [...] ")}`);
  }

  if (extra?.taskTitles && extra.taskTitles.length > 0) {
    supplementary.push(`Session tasks: ${extra.taskTitles.join("; ")}`);
  }

  if (extra?.sessionName) {
    supplementary.push(`Current session: ${extra.sessionName}`);
  }

  if (extra?.activeSessionNames && extra.activeSessionNames.length > 0) {
    supplementary.push(`Other active sessions: ${extra.activeSessionNames.join("; ")}`);
  }

  if (supplementary.length > 0) {
    parts.push(`<SESSION_CONTEXT>\n${supplementary.join("\n")}\n</SESSION_CONTEXT>`);
    parts.push("");
  }

  parts.push(`<TRANSCRIPT>\n${rawTranscript}\n</TRANSCRIPT>`);

  return parts.join("\n");
}

// ─── STT prompt construction ─────────────────────────────────────────────────

export interface SttPromptInput {
  /** Task titles from the session auto-namer (highest priority context). */
  taskHistory?: SessionTaskEntry[];
  /** Session display name. */
  sessionName?: string;
  /** Names of other active sessions (vocabulary from the user's workspace). */
  activeSessionNames?: string[];
  /** Text before the cursor in the composer (for mid-prompt voice insertion). */
  composerBefore?: string;
  /** Text after the cursor in the composer. */
  composerAfter?: string;
  /** Full message history for extracting recent user messages. */
  messageHistory?: BrowserIncomingMessage[] | null;
}

/**
 * Build a prompt string for the STT model (gpt-4o-mini-transcribe).
 *
 * Optimized for information density — every token should carry vocabulary signal.
 * The STT model uses this text purely for vocabulary recognition, not instruction following.
 *
 * Format (labeled sections for structure):
 *   1. Tasks: comma-separated task titles (highest density: file names, features, libraries)
 *   2. Session: current session name
 *   3. Sessions: other meaningful session names (auto-generated names filtered out)
 *   4. Composer surrounding text (for mid-prompt voice insertion)
 *   5. Conversation: recent turns in chat format (User: / Assistant:)
 *
 * Returns empty string if no useful context is available.
 */
export function buildSttPrompt(input: SttPromptInput): string {
  const parts: string[] = [];
  let remaining = STT_PROMPT_MAX_CHARS;

  // Helper: append text if it fits, returns false when budget exhausted
  const addLine = (text: string): boolean => {
    if (text.length > remaining) {
      if (remaining > 20) {
        parts.push(trunc(text, remaining));
        remaining = 0;
      }
      return false;
    }
    parts.push(text);
    remaining -= text.length + 1; // +1 for newline
    return remaining > 0;
  };

  // 1. Task titles — highest density vocabulary (file names, features, libraries)
  if (input.taskHistory && input.taskHistory.length > 0) {
    const seen = new Set<string>();
    const titles: string[] = [];
    for (let i = input.taskHistory.length - 1; i >= 0; i--) {
      const t = input.taskHistory[i].title;
      if (!seen.has(t)) {
        seen.add(t);
        titles.push(t);
      }
    }
    if (!addLine("Tasks: " + trunc(titles.join(", "), 800))) return parts.join("\n");
  }

  // 2. Session name
  if (input.sessionName && !isAutoGeneratedName(input.sessionName)) {
    if (!addLine("Session: " + input.sessionName)) return parts.join("\n");
  }

  // 3. Other session names — filtered, deduplicated, limited
  if (input.activeSessionNames && input.activeSessionNames.length > 0) {
    const filtered = filterSessionNames(
      input.activeSessionNames.filter((n) => n !== input.sessionName),
      MAX_STT_SESSION_NAMES,
    );
    if (filtered.length > 0) {
      if (!addLine("Sessions: " + filtered.join(", "))) return parts.join("\n");
    }
  }

  // 4. Composer surrounding text
  if (input.composerBefore || input.composerAfter) {
    const pieces: string[] = [];
    if (input.composerBefore) pieces.push(trunc(input.composerBefore.trim(), 500));
    if (input.composerAfter) pieces.push(trunc(input.composerAfter.trim(), 500));
    if (!addLine(pieces.join(" [...] "))) return parts.join("\n");
  }

  // 5. Recent conversation turns in chat format (User: / Assistant:)
  //    Including assistant messages helps the STT recognize vocabulary from questions
  //    the user might be verbally answering.
  if (input.messageHistory && remaining > 50) {
    const turns: Array<{ role: "User" | "Assistant"; text: string }> = [];
    for (let i = input.messageHistory.length - 1; i >= 0 && remaining > 20; i--) {
      const msg = input.messageHistory[i];
      let content = "";
      let role: "User" | "Assistant";
      if (msg.type === "user_message") {
        content = typeof (msg as { content?: unknown }).content === "string"
          ? (msg as { content: string }).content
          : "";
        role = "User";
        // Skip orchestrator noise
        if (content && isOrchestratorNoise(content)) continue;
      } else if (msg.type === "assistant") {
        const parentId = (msg as { parent_tool_use_id?: string | null }).parent_tool_use_id;
        if (parentId) continue;
        const blocks = (msg as { message?: { content?: ContentBlock[] } }).message?.content;
        if (Array.isArray(blocks)) {
          content = extractAssistantText(blocks);
        }
        role = "Assistant";
      } else {
        continue;
      }
      if (!content.trim()) continue;
      const truncated = trunc(content.trim(), STT_PROMPT_MAX_MSG_CHARS);
      const line = `${role}: ${truncated}`;
      if (line.length + 1 > remaining) break;
      turns.push({ role, text: truncated });
      remaining -= line.length + 1;
    }
    if (turns.length > 0) {
      turns.reverse();
      for (const t of turns) {
        parts.push(`${t.role}: ${t.text}`);
      }
    }
  }

  return parts.join("\n");
}

// ─── LLM call ───────────────────────────────────────────────────────────────

/** Result from callEnhancementLLM — either the enhanced text or an error message. */
type LLMCallResult =
  | { ok: true; text: string }
  | { ok: false; error: string };

/**
 * Call an OpenAI-compatible chat completions API to enhance the transcript.
 * Returns the enhanced text on success, or an error message on failure.
 */
async function callEnhancementLLM(
  prompt: string,
  config: TranscriptionConfig,
  apiKey: string,
): Promise<LLMCallResult> {
  const baseUrl = (config.baseUrl || "https://api.openai.com/v1").replace(/\/+$/, "");
  const model = config.enhancementModel || "gpt-5-mini";

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), ENHANCEMENT_TIMEOUT_MS);

    const res = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: prompt },
        ],
        max_completion_tokens: 1000,
        reasoning_effort: "low",
      }),
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      const errorMsg = `API error ${res.status}: ${body.slice(0, 300) || res.statusText}`;
      console.warn(`[transcription-enhancer] ${errorMsg}`);
      return { ok: false, error: errorMsg };
    }

    const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const text = json.choices?.[0]?.message?.content?.trim();
    if (!text) return { ok: false, error: "Empty response from LLM" };
    return { ok: true, text };
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.warn("[transcription-enhancer] LLM call failed:", errorMsg);
    return { ok: false, error: errorMsg };
  }
}

// ─── Public API ─────────────────────────────────────────────────────────────

export interface EnhancementResult {
  /** The final text (enhanced or raw fallback). */
  text: string;
  /** The original Whisper output (only set when enhancement was attempted). */
  rawText?: string;
  /** Whether LLM enhancement was actually applied. */
  enhanced: boolean;
  /** Debug info about the enhancement call (for debug panel). */
  _debug?: {
    model: string;
    systemPrompt: string;
    userMessage: string;
    enhancedText: string | null;
    durationMs: number;
    skipReason?: string;
  };
}

/**
 * Enhance a raw transcript using conversation context from the active session.
 *
 * Returns the raw text unchanged (with enhanced=false) when:
 * - The transcript is too short (< 3 words)
 * - No context is available (no conversation turns AND no supplementary context)
 * - Enhancement is disabled in config
 * - The LLM call fails
 * - The LLM output looks like hallucination (> 3x original length)
 */
export async function enhanceTranscript(
  rawText: string,
  history: BrowserIncomingMessage[] | null,
  config: TranscriptionConfig,
  apiKey: string,
  extra?: EnhancementContextInput,
): Promise<EnhancementResult> {
  const model = config.enhancementModel || "gpt-5-mini";

  // Skip if enhancement is disabled
  if (!config.enhancementEnabled) {
    return { text: rawText, enhanced: false, _debug: { model, systemPrompt: SYSTEM_PROMPT, userMessage: "", enhancedText: null, durationMs: 0, skipReason: "disabled" } };
  }

  // Skip for very short transcripts
  const wordCount = rawText.trim().split(/\s+/).length;
  if (wordCount < MIN_WORDS_FOR_ENHANCEMENT) {
    return { text: rawText, enhanced: false, _debug: { model, systemPrompt: SYSTEM_PROMPT, userMessage: "", enhancedText: null, durationMs: 0, skipReason: "too short" } };
  }

  // Build context from session history
  const conversationContext = history ? buildTranscriptionContext(history) : "";

  // Check if we have any meaningful context at all
  const hasExtra = !!(extra?.composerBefore || extra?.composerAfter || extra?.taskTitles?.length || extra?.sessionName || extra?.activeSessionNames?.length);
  if (!conversationContext && !hasExtra) {
    return { text: rawText, enhanced: false, _debug: { model, systemPrompt: SYSTEM_PROMPT, userMessage: "", enhancedText: null, durationMs: 0, skipReason: "no context" } };
  }

  // Build prompt and call LLM
  const prompt = buildEnhancementPrompt(rawText, conversationContext, extra);
  const t0 = Date.now();
  const llmResult = await callEnhancementLLM(prompt, config, apiKey);
  const durationMs = Date.now() - t0;

  if (!llmResult.ok) {
    return { text: rawText, enhanced: false, _debug: { model, systemPrompt: SYSTEM_PROMPT, userMessage: prompt, enhancedText: null, durationMs, skipReason: llmResult.error } };
  }

  const enhanced = llmResult.text;

  // Hallucination guard: if the enhanced text is way longer than the raw, discard it
  if (enhanced.length > rawText.length * HALLUCINATION_LENGTH_RATIO) {
    console.warn(
      `[transcription-enhancer] Discarding hallucinated output (${enhanced.length} chars vs ${rawText.length} raw)`,
    );
    return { text: rawText, enhanced: false, _debug: { model, systemPrompt: SYSTEM_PROMPT, userMessage: prompt, enhancedText: enhanced, durationMs, skipReason: "hallucination guard" } };
  }

  return { text: enhanced, rawText, enhanced: true, _debug: { model, systemPrompt: SYSTEM_PROMPT, userMessage: prompt, enhancedText: enhanced, durationMs } };
}

// ─── Debug log (in-memory, for Settings debug panel) ─────────────────────────

export interface TranscriptionLogEntry {
  id: number;
  timestamp: number;
  sessionId: string | null;
  /** STT phase */
  sttModel: string;
  sttDurationMs: number;
  rawTranscript: string;
  audioSizeBytes: number;
  /** Prompt sent to the STT model to guide vocabulary recognition. */
  sttPrompt: string;
  /** Enhancement phase (null if not attempted) */
  enhancement: {
    model: string;
    systemPrompt: string;
    userMessage: string;
    enhancedText: string | null;
    durationMs: number;
    skipReason?: string;
  } | null;
}

const MAX_LOG_ENTRIES = 50;
let logIdCounter = 0;
const transcriptionLog: TranscriptionLogEntry[] = [];

/** Add a transcription log entry. Called from routes.ts after each transcription. */
export function addTranscriptionLogEntry(entry: Omit<TranscriptionLogEntry, "id" | "timestamp">): TranscriptionLogEntry {
  const full = { ...entry, id: ++logIdCounter, timestamp: Date.now() };
  transcriptionLog.push(full);
  if (transcriptionLog.length > MAX_LOG_ENTRIES) {
    transcriptionLog.splice(0, transcriptionLog.length - MAX_LOG_ENTRIES);
  }
  return full;
}

/** List all log entries (lightweight: no sttPrompt, system prompt, or user message). Newest first. */
export function getTranscriptionLogIndex(): Array<Omit<TranscriptionLogEntry, "sttPrompt" | "enhancement"> & {
  enhancement: Omit<NonNullable<TranscriptionLogEntry["enhancement"]>, "systemPrompt" | "userMessage"> | null;
}> {
  return transcriptionLog
    .map((entry) => {
      const { sttPrompt: _p, enhancement, ...rest } = entry;
      if (!enhancement) return { ...rest, enhancement: null };
      const { systemPrompt: _s, userMessage: _u, ...enhRest } = enhancement;
      return { ...rest, enhancement: enhRest };
    })
    .reverse();
}

/** Get a single log entry by ID (includes full details). */
export function getTranscriptionLogEntry(id: number): TranscriptionLogEntry | undefined {
  return transcriptionLog.find((e) => e.id === id);
}

// ─── Test helpers ───────────────────────────────────────────────────────────

export const _testHelpers = {
  SYSTEM_PROMPT,
  MAX_TURNS,
  MAX_USER_MSG_CHARS,
  MAX_ASSISTANT_TEXT_CHARS,
  MIN_WORDS_FOR_ENHANCEMENT,
  HALLUCINATION_LENGTH_RATIO,
  STT_PROMPT_MAX_CHARS,
  STT_PROMPT_MAX_MSG_CHARS,
  MAX_STT_SESSION_NAMES,
  MAX_ENHANCEMENT_SESSION_NAMES,
  trunc,
  extractAssistantText,
  isAutoGeneratedName,
  isOrchestratorNoise,
  buildTranscriptionContext,
  buildEnhancementPrompt,
  buildSttPrompt,
};
