export interface SidebarSessionItem {
  id: string;
  claimedQuestStatus?: string;
  claimedQuestVerificationInboxUnread?: boolean;
  model: string;
  cwd: string;
  gitBranch: string;
  isContainerized: boolean;
  gitAhead: number;
  gitBehind: number;
  linesAdded: number;
  linesRemoved: number;
  gitStatusRefreshedAt?: number;
  gitStatusRefreshError?: string | null;
  isConnected: boolean;
  status: "idle" | "running" | "compacting" | "reverting" | null;
  sdkState: "starting" | "connected" | "running" | "exited" | null;
  createdAt: number;
  archived: boolean;
  archivedAt?: number;
  backendType: "claude" | "codex" | "claude-sdk";
  repoRoot: string;
  permCount: number;
  pendingTimerCount?: number;
  notificationUrgency?: "needs-input" | "review" | null;
  activeNotificationCount?: number;
  notificationStatusVersion?: number;
  notificationStatusUpdatedAt?: number;
  cronJobId?: string;
  cronJobName?: string;
  isWorktree?: boolean;
  worktreeExists?: boolean;
  worktreeDirty?: boolean;
  worktreeCleanupStatus?: "pending" | "done" | "failed";
  worktreeCleanupError?: string;
  askPermission?: boolean;
  idleKilled?: boolean;
  lastActivityAt?: number;
  lastUserMessageAt?: number;
  isOrchestrator?: boolean;
  herdedBy?: string;
  sessionNum?: number | null;
  reviewerOf?: number;
}
